version: "3.7"
services:
  postgres:
    image: postgres:16
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  dynamodb:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    ports:
      - '8000:8000'
    volumes:
      - './.dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal

  dynamodb_init:
    depends_on:
      - dynamodb
    image: amazon/aws-cli
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=local
    command: >-
      dynamodb create-table
          --endpoint-url http://dynamodb:8000
          --table-name clap
          --attribute-definitions
              AttributeName=key,AttributeType=S
          --key-schema
              AttributeName=key,KeyType=HASH
          --billing-mode PAY_PER_REQUEST

