version: '3.7'
services:
    websockets:
        build:
            context: ./server-websockets
            dockerfile: Dockerfile
        command: server-websockets
        init: true
        ports:
            - '9000:9000'
