version: "3.7"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - ON_CREATE_DB=clap
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./.mysql-data:/var/lib/mysql

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - ./.minio-data:/data
    command: server --console-address ":9090" /data
