AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RoleArn:
    Type: String
  S3Bucket:
    Type: String
  GitSha:
    Type: String
  BranchHash:
    Type: String
  AppSecret:
    Type: String
  DatabaseUrl:
    Type: String
Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: clap-${{ Ref(BranchHash) }}
      Runtime: nodejs22.x
      Architecture: arm64
      MemorySize: 256
      Timeout: 10
      Role: ${{ Ref(RoleArn) }}
      Handler: index.handler
      Code:
        S3Bucket: ${{ Ref(S3Bucket) }}
        S3Key: ${{ Ref(BranchHash) }}/app_${{ Ref(GitSha) }}.zip
      Environment:
        Variables:
          HOST_URL: https://${{ Ref(BranchHash) }}.preview-clap.daviddev.link
          APP_SECRET: ${{ Ref(AppSecret) }}
          DATABASE_URL: ${{ Ref(DatabaseUrl) }}
          DYNAMODB_TABLE_NAME: clap
