name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    types: [completed]
concurrency:
  group: deploy-group
  cancel-in-progress: true
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
